# Generated by Django 5.0.4 on 2024-06-14 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование доски', max_length=50, verbose_name='Наименование доски')),
                ('img', models.CharField(verbose_name='Картинка доски(фон)')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Введите Имя', max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Введите Фамилию', max_length=50, null=True, verbose_name='Фамилия')),
                ('nick_name', models.CharField(error_messages={'unique': 'Такой Никнейм уже есть'}, help_text='Введите Никнейм', max_length=50, unique=True, verbose_name='Никнейм')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'участники',
                'ordering': ['nick_name'],
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование колонки', max_length=50, verbose_name='Наименование колонки')),
                ('order', models.IntegerField(help_text='Номер позиции', null=True, verbose_name='Номер позиции колонки')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column', to='trello.dashboard')),
            ],
            options={
                'verbose_name': 'Колонку',
                'verbose_name_plural': 'колонки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование карточки', max_length=50, verbose_name='Наименование карточки')),
                ('order', models.IntegerField(help_text='Введите номер позиции карточки', verbose_name='Номер позиции карточки')),
                ('column', models.ForeignKey(blank=True, help_text='Введите колонку к которой относится карточка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='trello.column', verbose_name='Колонка')),
                ('author', models.ForeignKey(help_text='Введите автора', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='trello.person', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Карточку',
                'verbose_name_plural': 'карточки',
                'ordering': ['order'],
            },
        ),
    ]
