# Generated by Django 5.0.4 on 2024-05-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.IntegerField(error_messages={'unique': 'Номер позиции повторяется'}, help_text='Номер позиции', null=True, unique=True, verbose_name='Номер позиции колонки'),
        ),
    ]
