# Generated by Django 5.0.4 on 2024-08-02 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['id'], 'verbose_name': 'Метка', 'verbose_name_plural': 'метки'},
        ),
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(help_text='Введите текст', max_length=500, null=True, verbose_name='Текст описания карточки'),
        ),
        migrations.AlterField(
            model_name='dashboarduserrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dashboard', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('text', models.TextField(help_text='Введите наименование цветовой метки', max_length=500, verbose_name='Наименование цветовой метки')),
                ('author', models.ForeignKey(blank=True, help_text='Введите пользователя к которой описывает действие', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Действия',
                'verbose_name_plural': 'действие',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='trello.activity', verbose_name='Действия'),
        ),
    ]
