# Generated by Django 5.0.4 on 2024-06-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='img',
            field=models.CharField(null=True, verbose_name='Картинка доски(фон)'),
        ),
    ]
