# Generated by Django 5.0.4 on 2024-05-18 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='author',
            field=models.ForeignKey(help_text='Введите автора', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='trello.person', verbose_name='Автор'),
        ),
    ]
