# Generated by Django 5.0.4 on 2024-05-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_alter_column_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='order',
            field=models.IntegerField(help_text='Номер позиции', null=True, verbose_name='Номер позиции колонки'),
        ),
    ]
