# Generated by Django 5.0.4 on 2024-06-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_alter_dashboard_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='img',
            field=models.ImageField(max_length=200, null=True, upload_to='', verbose_name='Картинка доски(фон)'),
        ),
    ]
