# Generated by Django 5.0.4 on 2024-05-22 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_alter_cards_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Columns',
            new_name='Column',
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование карточки', max_length=50, verbose_name='Наименование карточки')),
                ('order', models.IntegerField(help_text='Введите номер позиции карточки', verbose_name='Номер позиции карточки')),
                ('author', models.ForeignKey(help_text='Введите автора', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='trello.person', verbose_name='Автор')),
                ('column', models.ForeignKey(blank=True, help_text='Введите колонку к которой относится карточка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='trello.column', verbose_name='Колонка')),
            ],
            options={
                'verbose_name': 'Карточку',
                'verbose_name_plural': 'карточки',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
