# Generated by Django 5.0.4 on 2024-08-07 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_alter_label_options_card_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(max_length=200, null=True, upload_to='', verbose_name='Фото пользователя'),
        ),
    ]
