# Generated by Django 5.0.4 on 2024-08-09 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0003_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Введите пользователя к которой описывает действие', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
