# Generated by Django 5.0.4 on 2024-06-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0003_alter_dashboard_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'verbose_name': 'Дашборд', 'verbose_name_plural': 'дашборды'},
        ),
    ]
