# Generated by Django 5.0.4 on 2024-08-11 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0004_alter_activity_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='card',
            field=models.ForeignKey(blank=True, help_text='Введите карточку к которой относится действие', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='trello.card', verbose_name='Карточка'),
        ),
    ]
