# Generated by Django 5.0.4 on 2024-08-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0006_remove_activity_text_activity_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
