# Generated by Django 5.0.4 on 2024-08-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0008_alter_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='execute',
            field=models.BooleanField(default=False, verbose_name='выполнить до срока'),
        ),
    ]
