# Generated by Django 5.0.4 on 2024-09-10 23:04

import django.db.models.deletion
import trello.models_functions.upload_files_img
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0008_alter_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='execute',
            field=models.BooleanField(default=False, verbose_name='выполнить до срока'),
        ),
        migrations.CreateModel(
            name='CardFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Введите имя файла', max_length=50, null=True, verbose_name='Имя файла')),
                ('size', models.IntegerField(help_text='Введите размер к файла', null=True, verbose_name='Размер файла')),
                ('extension', models.CharField(blank=True, help_text='Введите расширение файла', max_length=50, null=True, verbose_name='расширение файла')),
                ('date_upload', models.DateTimeField(auto_now=True, null=True)),
                ('file_url', models.FileField(blank=True, null=True, upload_to=trello.models_functions.upload_files_img.upload_to_files)),
                ('card', models.ForeignKey(blank=True, help_text='Введите карточку к которой относится файл', on_delete=django.db.models.deletion.CASCADE, related_name='card_file', to='trello.card', verbose_name='Карточка')),
            ],
        ),
        migrations.CreateModel(
            name='CardImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Введите имя фото', max_length=50, null=True, verbose_name='Имя фото')),
                ('size', models.IntegerField(help_text='Введите размер фото', null=True, verbose_name='Размер фото')),
                ('extension', models.CharField(blank=True, help_text='Введите расширение фото', max_length=50, null=True, verbose_name='расширение фото')),
                ('date_upload', models.DateTimeField(auto_now=True, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=trello.models_functions.upload_files_img.upload_to_images)),
                ('card', models.ForeignKey(blank=True, help_text='Введите карточку к которой относится фото', on_delete=django.db.models.deletion.CASCADE, related_name='card_img', to='trello.card', verbose_name='Карточка')),
            ],
        ),
    ]
