# Generated by Django 5.0.4 on 2024-09-15 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0010_imageextension_cardfile_image_cardimg_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, help_text='Введите ссылку', max_length=200, null=True, verbose_name='Имя ссылки')),
                ('description', models.CharField(blank=True, help_text='Введите описание ссылки', max_length=200, null=True, verbose_name='описание ссылки')),
                ('card', models.ForeignKey(blank=True, help_text='Введите карточку к которой относится ссылка', on_delete=django.db.models.deletion.CASCADE, related_name='card_link', to='trello.card', verbose_name='Карточка')),
            ],
        ),
    ]
