# Generated by Django 5.0.4 on 2024-09-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0012_cardlink_favicon_cardlink_first_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlink',
            name='description',
            field=models.CharField(blank=True, help_text='Введите описание ссылки', max_length=500, null=True, verbose_name='описание ссылки'),
        ),
        migrations.AlterField(
            model_name='cardlink',
            name='favicon',
            field=models.CharField(blank=True, help_text='Введите ссылку для фавикона', max_length=200, null=True, verbose_name='Имя ссылки для фавикона'),
        ),
        migrations.AlterField(
            model_name='cardlink',
            name='text',
            field=models.CharField(blank=True, help_text='Введите ссылку', max_length=500, null=True, verbose_name='Имя ссылки'),
        ),
    ]
