# Generated by Django 5.0.4 on 2024-09-26 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0013_alter_cardlink_description_alter_cardlink_favicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Введите имя фото', max_length=200, verbose_name='Имя фото')),
                ('size', models.IntegerField(help_text='Введите размер фото', null=True, verbose_name='Размер фото')),
                ('extension', models.CharField(blank=True, help_text='Введите расширение фото', max_length=50, null=True, verbose_name='расширение фото')),
                ('date_upload', models.DateTimeField(auto_now=True, null=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Служебное фото',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['id'], 'verbose_name': 'Действия', 'verbose_name_plural': 'Действие'},
        ),
        migrations.AlterModelOptions(
            name='cardfile',
            options={'ordering': ['id'], 'verbose_name': 'Файл карточки'},
        ),
        migrations.AlterModelOptions(
            name='cardimg',
            options={'ordering': ['id'], 'verbose_name': 'Фото карточки'},
        ),
        migrations.AlterModelOptions(
            name='cardlink',
            options={'ordering': ['id'], 'verbose_name': 'Ссылка карточки'},
        ),
        migrations.AlterModelOptions(
            name='imageextension',
            options={'ordering': ['id'], 'verbose_name': 'Расширение фото'},
        ),
        migrations.AlterField(
            model_name='carduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_card', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
