# Generated by Django 5.0.4 on 2024-11-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0015_alter_activity_options_invituserdashboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='label_text',
            field=models.CharField(help_text='Введите текст метки', max_length=100, null=True, verbose_name='Текст для метки'),
        ),
    ]
