# Generated by Django 5.0.4 on 2024-11-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0015_alter_activity_options_invituserdashboard_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboarduserrole',
            options={'verbose_name': 'роли юзеров на доске', 'verbose_name_plural': 'Роли Пользователей на Доске'},
        ),
    ]
