# Generated by Django 5.0.4 on 2024-11-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0016_alter_dashboarduserrole_options'),
        ('trello', '0016_card_label_text'),
    ]

    operations = [
    ]
